export const COP_THRESHOLDS = {
    EXCELLENT: 0.8,
    GOOD: 0.5,
    POOR: 0.2,
    VERY_POOR: 0.0, // Implicit lower bound
};

export const DEFAULT_WEIGHTS = {
    PRICE_SUMMER: 0.7,
    PRICE_WINTER: 0.4,
    PRICE_TRANSITION: 0.5,
    COP_EFFICIENCY_BONUS_HIGH: 0.3,
    COP_EFFICIENCY_BONUS_MEDIUM: 0.2,
};

export const COMFORT_CONSTANTS = {
    DEFAULT_MIN_TEMP: 18,
    DEFAULT_MAX_TEMP: 23,
    DEFAULT_MIN_TEMP_ZONE2: 18,
    DEFAULT_MAX_TEMP_ZONE2: 23,
    DEFAULT_MIN_TANK_TEMP: 40,
    DEFAULT_MAX_TANK_TEMP: 60,
    DEFAULT_TEMP_STEP: 0.5,
    DEFAULT_TEMP_STEP_ZONE2: 1.0,
    DEFAULT_TANK_TEMP_STEP: 1.0,
    DEFAULT_DEADBAND: 0.5,
    DEFAULT_MIN_SETPOINT_CHANGE_MINUTES: 30,
};

export const OPTIMIZATION_CONSTANTS = {
    MIN_SAVINGS_FOR_LEARNING: 0.05, // NOK/EUR etc
    MAX_RECONNECT_ATTEMPTS: 3,
    RECONNECT_DELAY_MS: 5000,
};
