name: CI

on:
  push:
    branches: [ main, improvements ]
  pull_request:
    branches: [ main, improvements ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run build:check
      - name: Run tests
        run: npm test --silent
